### ISSUE TITLE
NodeError: Request path contains unescaped characters

### ISSUE THREAD

**Issue by josephrocca** [bitinn/node-fetch#531] opened 2018-10-07 12:04 UTC
Forgive me if this has already been brought up, but I couldn't find any previous issue about it.

Try going to `example.com` and opening up the console and running this:
```javascript
await fetch("http://example.com?foo=网").then(r => r.text());
```
No error, all is well.

Now check out [this runkit example](https://runkit.com/embed/ykx0f77bwrbn).

Here's the error:
```
NodeError: Request path contains unescaped characters
at new ClientRequest in core _http_client.js — line 114
at http.get in core http.js — line 41
 in node-fetch/lib/index.js — line 1327
at new Promise in core  — line 0
at Object.fetch in node-fetch/lib/index.js — line 1319
```

I guess the browser spec of fetch automatically escapes characters or something? I'm not sure as I haven't looking into it. It would be nice if there were consistency here in any case.

**EDIT:** This error doesn't occur in Node.js 8.x (only 10.x), so I guess there was a change in the http/https libs or something.

**Comment by bitinn** [comment] 2018-10-07 16:03
see if this issue helps: #245

**Comment by josephrocca** [comment] 2018-10-07 17:29
Good to know that `require('url').URL` is an easy way to solve it. Why not use that behind the scenes in `node-fetch` so you get consistency with the browser? In any, case thanks for your work on this! If you're happy with the way it currently works, please go ahead and close this issue - it's not a big deal for me - just reporting to help the lib.

**Comment by jimmywarting** [comment] 2018-10-07 23:17
> `require('url').URL` is an easy way to solve it. Why not use that behind the scenes in node-fetch so you get consistency with the browser.

I think that is a grate idea. 

But the URL constructor is only available since v7 and we target LTS (right now v6)

|  Version  |  Changes  |
|:---|:---|
| v10.0.0 | The class is now available on the global object. |
| v7.0.0 | Added in: v7.0.0 |

We could either include a polyfill or do feature detection if we don't wan't a other large dependency and make it as a progressive enhancement

```js
const { URL } = require('url')
const urlSupported = !!URL
```

I don't believe either that some URL polyfill are handling the utf8 encoding correctly either so...

**Comment by josephrocca** [comment] 2018-10-08 04:32
The progressive enhancement route is a good idea I think, especially since versionsnove 6.x and node 8.x don't seem to give errors for these sorts of URLs. It only started happening in node 10.x for me.

**Comment by wzhouwzhou** [comment] 2018-10-13 06:00
Good evening,

> But the URL constructor is only available since v7 and we target LTS (right now v6)
> 
> Version	Changes
> v10.0.0	The class is now available on the global object. 
> v7.0.0	Added in: v7.0.0

@jimmywarting it appears to me that node v8 is actually the LTS version, and as a matter of fact has been for almost a year now; it would be ideal to actually target LTS if you mean to and not v6 which is not LTS. After all, with v8.9.0 Carbon entering the v8.x major semver line, 8.x will remain in Active LTS until April 2019, and as of the time of writing this v10.12.0 is already published as the Latest Current Version.

I have attached some resources for further reading for anyone particularly interested.
[NodeJS Latest LTS Version Download Page](https://nodejs.org/en/download/)
[NodeJS Latest Current Version Download Page](https://nodejs.org/en/download/current/)
[Node v8.9.0 Release Blog](https://nodejs.org/en/blog/release/v8.9.0/)
![Release dated October 31, 2017](https://i.imgur.com/OlclK6A.png)

![LTS vs Nightly](https://i.imgur.com/MrAkvmc.png)

![Node recommends v8 as LTS](https://i.imgur.com/F88Pmms.png)

I agree with @josephrocca's fantastic suggestion regarding consistency across runtimes and versions. Regarding progressive enhancements or deferred require, however, I am concerned whether more robust checks than `!!URL` would be needed.

Thank you for taking the time to read through this. I look forward to upcoming updates as you continue to adapt to user needs and a constantly evolving runtime.

Best,
~William

**Comment by wzhouwzhou** [comment] 2018-10-13 19:48
Greetings,

I never disputed whether v6 is supported or not; v6 retired from active LTS as "maintenance" LTS with v8 labeled as the current "active" LTS version. The matter still stands that, the fact that node v11.x, a version 5 major semver releases ahead of v6, is already available as nightly and has a pending official release date, goes to show how significant the fact that v6  transitioned away from active LTS is, and how important a timely response to this issue is.

~William

**Comment by bitinn** [comment] 2018-11-05 07:36
I am closing this as a duplicate of #245

**Closed by bitinn** 2018-11-05 07:36 UTC
Labels: bug, enhancement, good first issue
