### ISSUE TITLE
v2.0.0 Getting error: 'not a legal HTTP header value' on url that works in Chrome

### ISSUE THREAD

**Issue by geekrelief** [bitinn/node-fetch#401] opened 2018-02-16 03:35 UTC
When I attempt a fetch on https://www.bitstamp.net/api/v2/ticker/xrpusd/, I get an error
throw new TypeError(`${value} is not a legal HTTP header value`); 
on line 741 in libs/index.js
The value is:

```
___utmvaDlumyLc=EqedchD; path=/; Max-Age=900
```

The offending character has a char code of 1 at index 19 which is empty between the 'e' and 'd' chars.

I had to comment out the checkInvalidHeaderChar function in sanitizeValue to get the fetch to work.

**Comment by TimothyGu** [comment] 2018-02-17 08:25
I cannot reproduce this issue just by fetching that URL. Can you provide the code to reproduce?

**Comment by geekrelief** [comment] 2018-02-18 18:15
Yeah I just created a new folder:
npm init
npm install node-fetch # node-fetch@2.0.0
then in app.js I added:

```
const fetch = require('node-fetch')

fetch("https://www.bitstamp.net/api/v2/ticker/xrpusd/", {
    method: 'GET'
})
.then(res=>res.json())
.then(res => {
    console.log("response\n%o", res)
})
.catch(error => console.log('Get failed', error))
```
then node app.js gives this:

> /Users/mugen/Desktop/dev/nodetest/node_modules/node-fetch/lib/index.js:741
> 		throw new TypeError(`${value} is not a legal HTTP header value`);
> 		^
> 
> TypeError: ___utmvaDlumyLc=gjdyEHQ; path=/; Max-Age=900 is not a legal HTTP header value
>     at sanitizeValue (/Users/mugen/Desktop/dev/nodetest/node_modules/node-fetch/lib/index.js:741:9)
>     at Headers.append (/Users/mugen/Desktop/dev/nodetest/node_modules/node-fetch/lib/index.js:873:38)
>     at ClientRequest.<anonymous> (/Users/mugen/Desktop/dev/nodetest/node_modules/node-fetch/lib/index.js:1424:15)
>     at ClientRequest.emit (events.js:160:13)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:548:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
>     at TLSSocket.socketOnData (_http_client.js:439:20)
>     at TLSSocket.emit (events.js:160:13)
>     at addChunk (_stream_readable.js:269:12)
>     at readableAddChunk (_stream_readable.js:256:11)

**Comment by bitinn** [comment] 2018-03-01 09:54
@geekrelief Hi, I gave it a try today and manage to produce your issue, but the cause is indeed the header being corrupted:

Try this `curl -I https://www.bitstamp.net/api/v2/ticker/xrpusd/ > test.txt`

And I got in `test.txt` (view with sublime text):

<img width="779" alt="screen shot 2018-03-01 at 17 51 57" src="https://user-images.githubusercontent.com/1484279/36838128-43423858-1d79-11e8-8b71-c8de4d8762f5.png">

See that `SOH`, that's a control character, it would be hidden when printed to console. It shouldn't be a part of header value.

https://en.wikipedia.org/wiki/Control_character

**Comment by bitinn** [comment] 2018-03-01 09:54
I think we can close this case.

**Closed by bitinn** 2018-03-01 09:54 UTC

**Comment by TimothyGu** [comment] 2018-03-04 21:29
Duplicate of https://github.com/bitinn/node-fetch/issues/411.

**Comment by dncrews** [comment] 2019-12-16 03:33
For the sake of future generations: if you have a newline in your value (e.g. AWS parameter store), you will get this same error.

**Comment by DJ-Architect** [comment] 2020-11-05 23:44
@dncrews  god thankyou so much

**Comment by gregbarcza** [comment] 2021-05-18 11:18
I've wasted +2 hours because of this. Shouldn't we implement a fix for this issue? :)

**Comment by jimmywarting** [comment] 2021-05-18 11:49
Maybe propose that the Header specification trims all key/values?

```js
new Headers([['foo\n', 's']]).get('foo')  // throws in chrome
new Headers([['foo\n'.trim(), 's']]).get('foo') // works  in chrome
```
I found some related https://github.com/whatwg/fetch/issues/757 when searching for trim

**Comment by juanpprieto** [comment] 2021-07-20 04:33
I was banging my head with this one too. In my case (sadly) I had a simple typo `a nested :` inside the header property name.

fixed by changing
```
 headers: {
   'x-authorization:👈': 12312313123
  }
  ```

to 
```
 headers: {
   'x-authorization': 12312313123
  }
  ```

**Comment by jimmywarting** [comment] 2021-07-20 08:56
Maybe should start helping out saying what the cause of it is and saying what is invalid about your string...

> the header `new TypeError(${'x-authorization:'} is not a legal HTTP header value, it can't contain ':')`

we have a issue open about #549

**Comment by Seanmclem** [comment] 2023-10-12 16:04
not a `\n` for me, but my issue was that my variable was wrapped in "quotes", and it didn't like that. So I removed them and re-saved. Fixed.

**Comment by maogongzi** [comment] 2024-09-08 15:03
> For the sake of future generations who will find this: if you have a newline at the end of your key (e.g. AWS parameter store), you will get this same error. You'll be able to tell without looking because the "is not a legal HTTP header value" will be on the next line, instead of inline.

It's 2024 and I still own you a thank you!

<img width="680" alt="Screenshot 2024-09-08 at 23 03 04" src="https://github.com/user-attachments/assets/6a489696-94be-4689-8797-f89b0b1a5181">
