### ISSUE TITLE
wish: add unix domain socket support

### ISSUE THREAD

**Issue by nahuel** [bitinn/node-fetch#336] opened 2017-08-30 15:52 UTC
Add the option to connect to a unix socket, like https://github.com/request/request#unix-domain-sockets

**Comment by TimothyGu** [comment] 2017-08-31 00:04
Do browsers support Unix domain sockets? We try to align with browsers, not always other Node.js libraries.

**Comment by nahuel** [comment] 2017-08-31 13:43
I think browsers doesn't support them, but node supports serving HTTP from a unix domain socket (https://nodejs.org/api/http.html#http_server_listen_path_callback ), making requests to them (https://nodejs.org/api/http.html#http_http_request_options_callback ) and many utilities like `curl` also support them.

**Comment by TimothyGu** [comment] 2017-08-31 14:20
I'm going to close this for the same reason we don't support `file:` URLs. Please search through other issues for the rationale on why that is the case, though we *should* perhaps document that somewhere more permanent.

**Closed by TimothyGu** 2017-08-31 14:21 UTC

**Comment by masaeedu** [comment] 2017-10-23 05:18
@TimothyGu This is unfortunate, because it makes it impossible to use `node-fetch` to communicate with a local docker instance (without doing some portmap gymnastics that permissions on a CI server may or may not allow).

**Comment by caub** [comment] 2018-09-19 17:38
in theory this could work:

```js
const http = require('http');
const fs = require('fs');

const agent = new http.Agent();
agent.createConnection({ fd: fs.openSync('/var/run/docker.sock', 'r') });

fetch('http:/v1.24/containers/json', { agent: myAgent }).then(console.log)
```
but I get `Error: ENXIO: no such device or address, open '/var/run/docker.sock'
    at Proxy.openSync`

**Comment by Qix-** [comment] 2018-10-28 17:57
Please reconsider this. Not having this functionality in `node-fetch` means having two implementations for HTTP handling.

Nobody is expecting a complete 1:1 parity with the w3 module - meaning, I don't think anyone would care or even notice if an extra option was available to specify the connection should be made over a domain socket.

Even if there was `require('node-fetch').unixSocket` or something like that - that would help immensely.

**Comment by cdoublev** [comment] 2018-11-19 10:14
@bitinn, Could you please give me some hints about how to test your providden solution? I might not have understand how to test it the right way...

My test setup is a NodeJS app listening on `/var/run/nodejs/nodejs.sock` proxyied by Nginx listening on port 8000 inside a Vagrant guest. Port 8000 and Vagrant are non important details but I'm mentioning them just in case.

```js
// test.js (inside the guest)
const fetch = require('node-fetch')
const { Agent } = require('http')

const agent = new Agent({ path: '/var/run/nodejs/nodejs.sock' })

fetch('http://0.0.0.0:8000/api/categories/index.json', { agent })
    .then(res => res.json())
    .then(console.log)
    .catch(console.log)
   // Output : { ...parsed JSON } and an entry is appended to Nginx access log.

fetch('/api/categories/index.json', { agent })
    .then(res => res.json())
    .then(console.log)
    .catch(console.log)
   // Output : Error: only absolute urls are supported
```

**Comment by bitinn** [comment] 2018-11-19 10:30
Your first example appear to work (network-wise). The error you got seems to suggest the JSON response was invalid JSON, you should post the full error.

(From my phone)

**Comment by bitinn** [comment] 2018-11-19 11:38
@cdoublev I guess the problem comes down to whether you can construct a "valid" absolute url that can go pass `url.parse` while satisfying the `http(s)` scheme requirement.

Due to lack of `context` and lack of Fetch Spec definition on non-`http` protocol, we only support `http(s)` scheme and absolute url.

I originally thought it might work if you construct the `url` in a way that can resolve properly. But maybe I am too optimistic about this.

Seeing how non-standard unix domain socket url are (I still don't know if `http+unix://` or `unix:` or `http://unix:` are valid, every tool only seem to support a fraction of them), I really don't think we will invest more time to support this feature.

**Comment by cdoublev** [comment] 2018-11-19 11:39
Ok, I'm fine with that. Thank you for your quick feed back.

**Comment by caub** [comment] 2018-11-19 16:02
just a note, I tried that with docker a few months ago:

```js
var fetch = require('node-fetch');
var agent = new http.Agent({ path: '/var/run/docker.sock' });
fetch('http:/v1.37/containers/json', {agent}).then(console.log); // .then is never invoked
```

**Comment by zkochan** [comment] 2019-03-07 23:51
Seems like [this fork](https://github.com/liangxingchen/node-fetch-unix) of node-fetch supports unix domain socket.

I am switching [pnpm](https://github.com/pnpm/pnpm/) from request/got to node-fetch. Unfortunatly, pnpm needs also the unix socket support, so I'll have to use a fork of node-fetch or create my own :cry:

**Comment by garkin** [comment] 2019-04-11 17:39
This was a major blow for my homebrew docker util. 🤷‍♂️
Any hints for alternative mainstream ajax library with unix://?

**Comment by ericvicenti** [comment] 2020-03-31 18:33
I thought node-fetch was a high-level http library, but now I need an alternative because of the *transport layer*?? I'm still talking HTTP!

For a bit of context, I want to use unix sockets in for tests so they can run in parallel without port conflicts. My http server is happily capable of attaching to a unix socket.. why can't the client??

I can switch to [got](https://www.npmjs.com/package/got) for my node.js usage, but this seems like a silly reason to ditch node-fetch...

**Comment by Qix-** [comment] 2020-04-01 19:14
@ericvicenti I commented above a few years ago about this, and since they have a hard stance against it, I switched all of my projects to `got` and haven't looked back. I recommend you do, too.

**Comment by joshbalfour** [comment] 2020-04-04 12:01
looks like i'll have to do the same, i found this which looks like it'll make the transition easier https://www.npmjs.com/package/got-fetch

**Comment by gwn** [comment] 2020-04-10 11:53
> Do browsers support Unix domain sockets? We try to align with browsers, not always other Node.js libraries.

Unix domain sockets are not a "Node.js" library. It's a feature of the unix platform.

I think the proper goal ought to be aligning with the fetch interface provided by the browsers; not blindly align with the "browser the platform". The point of this library is being platform-agnostic; but that doesn't necessarily justify leaving out support for platform specific features. What developers are looking for is one-fetch-libary-to-rule-them-all. If I have to switch libraries whenever I need a platform specific feature, what's the point?

**Comment by gwn** [comment] 2020-04-10 12:19
I mistook `node-fetch` with platform agnostic fetch libraries so my comments are a bit misaligned. But the argument still holds.

Let's make a correction:

The point of this library is having the same interface as the browsers' fetch; but that doesn't necessarily justify leaving out support for server-side features.

**Comment by elmerbulthuis** [comment] 2020-09-09 14:11
> Do browsers support Unix domain sockets? We try to align with browsers, not always other Node.js libraries.

Supporting unix sockets is not aligning with other libraries, it's aligning with the environment. And for node-fetch that is node.js.

I think not supporting unix socket via the agent is unexpected (btw also unnecessary) behavior and can therefore be considered a bug.

It's not that hard to fix. I would love to do it, but i guess there has been some effort already that will not be merged.

**Comment by elmerbulthuis** [comment] 2020-09-09 15:04
So in the end it seems that this is a bug (as in unexpected behavior). The problem is, however not with node-fetch!

Here we can read about the [http.Agent](https://nodejs.org/api/http.html#http_new_agent_options). The documentation says
```
options in socket.connect() are also supported.
```

Check out those options [here](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener). It says:
```
For IPC connections, available options are:

    path <string> Required. Path the client should connect to. See Identifying paths for IPC connections. If provided, the TCP-specific options above are ignored.
```

And yes, an IPC socket is a [unix socket](https://en.wikipedia.org/wiki/Unix_domain_socket)

So we can configure the agent to talk to a unix socket, just like explained earlier in this post. Only problem is that this does not work. But why?

Well, one reason is that the path option is set to null [in the constructor of the Agent](https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L89). The path option will always be null!

At some point, while making the actual request, the agent will call the [createConnection](https://nodejs.org/api/net.html#net_net_createconnection_options_connectlistener) function, via it's [createSocket](https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L296) method.

Now in this method look at this piece of code:
```
  options = { ...options, ...this.options };
  if (options.socketPath)
    options.path = options.socketPath;
```
Yes, the path property that was so brutally set to null in the constructor is set again! But with the value of the socketPath property of the options that we pass to the Agent (this.options).

So when we pass the unix path as a socketPath option to the agent, everything works as expected, so something like:
```
        const agent = new http.Agent({
            socketPath: "/var/run/docker.sock",
        });
```

After all this was a bug! But not in node-fetch. The node.js documentation is a bit off here.

I am very happy that can keep using node-fetch for everything http!

**Comment by h0tw4t3r** [comment] 2020-09-29 14:28
> So when we pass the unix path as a socketPath option to the agent, everything works as expected, so something like

I'm trying to connect to snap socket located in `/run/snapd.socket`, and that solution doesn't really work. I get `Failed to fetch net::ERR:REFUSED_CONNECTION` error, tried different variants such as `http://localhost/` and `http://0.0.0.0`.
Also I'm using TypeScript and looks like it lacks all `http.Agent` methods.
I'd love seeing support for unix sockets since Node.JS is slowly getting to PC appications.

**Comment by Bessonov** [comment] 2022-06-12 00:31
Not tested yet, but the native node's fetch [could support unix socket](https://github.com/nodejs/undici/blob/main/test/unix.js#L34) and there are some pointers [in the code](https://github.com/nodejs/node/blob/921ef9b/deps/undici/undici.js#L2797). And [no documentation](https://nodejs.org/api/globals.html#fetch) ATM.

**Comment by AndASM** [comment] 2022-09-28 00:53
> Not tested yet, but the native node's fetch [could support unix socket](https://github.com/nodejs/undici/blob/main/test/unix.js#L34) and there are some pointers [in the code](https://github.com/nodejs/node/blob/921ef9b/deps/undici/undici.js#L2797). And [no documentation](https://nodejs.org/api/globals.html#fetch) ATM.

Here, have an unofficial example. It's still fetch, so it's still sending http requests. I'm using it for Apollo GraphQL over a unix socket.
```typescript
// Node 18 uses undici fetch, so you don't have to import fetch. But you can.
import { Agent } from "undici";

// The URL must parse as a valid url, but the hostname doesn't matter for the connection.
// I've included a dummy value of... dummy. But you could use real host names if proxying, or route off the host name.
fetch("http://dummy/path/in/http/request/over/socket", {
  dispatcher: new Agent({
    connect: {
      socketPath: "/tmp/test-unix-socket"
    }
  }) 
});
```
