### ISSUE TITLE
Infinite responses cannot be handled

### ISSUE THREAD

**Issue by mika-fischer** [bitinn/node-fetch#438] opened 2018-03-28 17:14 UTC
AFAICT there's currently no way to close a request. My use-case is an infinite `text/event-stream` response that I have to abort manually.

See https://gist.github.com/mika-fischer/31b564ca299c838489f1bdbd5af9ef59 for a simple demonstration. Start the server with `node node-fetch-streaming-bug.js server` then try `node node-fetch-streaming-bug.js http`, which works and `node node-fetch-streaming-bug.js fetch` which hangs...

Also, the recent work on aborting doesn't help here if I understood it correctly, that's more about aborting before the response headers have arrived, right?

**Comment by TimothyGu** [comment] 2018-03-28 18:36
Duplicate of #203.

----

> Also, the recent work on aborting doesn't help here if I understood it correctly, that's more about aborting before the response headers have arrived, right?

Nope, aborting actually does quite a few things:

- End the request if it is still being sent out
- Throw out any response body already received but not yet consumed
- Destroy the socket used for this connection

What you are looking for is the last item in that list.

**Closed by TimothyGu** 2018-03-28 18:36 UTC
