### ISSUE TITLE
http2 library support

### ISSUE THREAD

**Issue by evert** [bitinn/node-fetch#560] opened 2018-12-10 21:25 UTC
I would like to use `node-fetch` with http2. My goal is to:

1. Create a caching layer for `node-fetch` that respects HTTP caching headers
2. Have node-fetch use http2 instead of http.
3. Hook into push events, so request and response pairs from node-fetch automatically 'warm' the cache.

I realize that #342 exists, but I don't think it's really worth waiting for a standard. The issue with http2 and push support is that in browsers, http2 is transparent and push already interacts with an existing cache. Because of these two facts the user-facing `fetch()` api doesn't need to make users of this api aware that http2 is used or that push occurred.

**Comment by bitinn** [comment] 2019-01-16 05:31
Hey @evert, sure, people wanted a HTTP 2 version, and I am aware of at least 2 implementations.

Both don't support HTTP 1.1 transparently.

Our concern remains that **node.js should be providing the transparent layer between HTTP 1/2, not us.** This is the same as the browsers, except their engineering team are payed to do that.

I am closing this a duplicate of #342

**Closed by bitinn** 2019-01-16 05:31 UTC

**Comment by tessus** [comment] 2019-11-05 04:26
> Both don't support HTTP 1.1 transparently.

It seems that https://github.com/grantila/fetch-h2 supports http/1.1 and h2 transparently.
