### ISSUE TITLE
headers not getting sent

### ISSUE THREAD

**Issue by omnidan** [bitinn/node-fetch#112] opened 2016-05-01 00:54 UTC
I have the following call:

```js
fetch('https://url:port/status',
  {
    headers: {
      'X-Token': 'XXX'
    }
  }
)
```

Which results in `401 Unauthorized`. However, the same call with `curl` works fine:

```
curl -H "X-Token: XXX" https://url:port/status
```

It seems like the headers are not getting sent with `node-fetch`.

**Comment by bitinn** [comment] 2016-05-01 01:30
We don't limit headers at all, do a simple test with http://httpbin.org/ or make a failing test cases would help.

**Comment by omnidan** [comment] 2016-05-01 14:13
@bitinn thanks for the suggestions - httpbin.org is very useful for debugging :grin:

This is very weird though - I got the requests to look exactly the same on httpbin, but it's still not working with `node-fetch` while it works fine with `curl`. Also, I'm trying to access the plex api (e.g. `/status/sessions`).

Any idea how I could further debug this?

**Comment by bitinn** [comment] 2016-05-01 14:20
hmmm, I can only imagine they demand a nicer user agent? check their robots.txt for example?

you might want to figure out if they provide more detailed error message somewhere? Seem more like a Plex issue to me than Node.js issue.

**Comment by omnidan** [comment] 2016-05-01 14:29
@bitinn actually I did set the `User-Agent` header to `curl/7.43.0` too so the requests are exactly the same.

Yeah I thought so too, but if the requests are exactly the same, why does `curl` work and `node-fetch` doesn't - very weird.

**Comment by bitinn** [comment] 2016-05-01 14:46
You might want to raise it to Plex people (if your requests are exactly the same, then either your network or plex is acting up), I will keep this open.

**Comment by mmocny** [comment] 2016-05-16 18:37
FYI it looks like node-fetch lowercases all headers instead of respecting case provides.  According to HTTP spec, they are supposed to be case-insensitive, so this should be fine, but some servers do this incorrectly.

We also just had an issue with a server which was doing case-sensitive lookup and we were at a loss why the headers were not being passed down, until we did a raw dump and realized the casing issue.

**Comment by bitinn** [comment] 2016-05-16 19:00
hmmm it could be the cause to OP's problem, httpbin.org might not output headers according to their original casing.

PS: not lowercasing within `node-fetch` might lead to user setting duplicate headers unknowingly, if we do change this behavior to allow uppercase, it would probably be a breaking change of some sort.

**Comment by bitinn** [comment] 2016-05-16 19:04
Ah Fetch Spec did suggest lower-casing header names https://fetch.spec.whatwg.org/#terminology-headers

**Comment by bitinn** [comment] 2016-05-25 19:01
there isn't much we can do for this issue, closing for now.

**Closed by bitinn** 2016-05-25 19:01 UTC

**Comment by omnidan** [comment] 2016-05-25 19:26
@bitinn
Maybe you could add a workaround that one can enable via `caseSensitive: true`. There isn't really much else you can do when APIs don't follow the spec. What do you think?

**Comment by bitinn** [comment] 2016-05-25 19:31
@omnidan we can't because we need `headers['key']` to be unique, `headers.get('A')` should be the same as `headers.get('a')`, and Fetch Spec has enforced lowercase key.

we also don't workaround API issues.

**Comment by omnidan** [comment] 2016-05-25 19:40
@bitinn Oh, that makes sense. Well, thanks for the help!
