### ISSUE TITLE
Node.js getaddrinfo ENOTFOUND only when requesting with node-fetch

### ISSUE THREAD

**Issue by victorsferreira** [bitinn/node-fetch#449] opened 2018-05-01 19:44 UTC
When I send a post request to this webserver I get the error:

> FetchError: request to http://soa...ProxySoap failed, reason: getaddrinfo ENOTFOUND soa soa:30289
>     at ClientRequest.<anonymous> (/home/projetos/login-backend/node_modules/node-fetch/index.js:133:11)
>     at ClientRequest.emit (events.js:160:13)
>     at Socket.socketErrorListener (_http_client.js:389:9)
>     at Socket.emit (events.js:160:13)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at process._tickCallback (internal/process/next_tick.js:152:19)

I can use Postman from this machine and Axios from my source code, and I don't get any errors. This error happens only with node-fetch. Is it a known issue? What can I do to make it work?

This is the request I'm sending with Node-Fetch:
```
this.fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'text/xml; charset=utf-8',
                'Content-Length': request.length
            },
            body: request,
            timeout: _timeout
        })
```

I'm sending an XML via POST to a SOAP service.

Extra info: i'm behind a corporate proxy. Is Node-Fetch relying on some configuration that Axios is not?!

Thanks

**Comment by gr2m** [comment] 2018-05-01 19:46
Is the URL you try to request accessible? If yes could you share it with us? If not, we would need some way to reproduce the problem you are running into

**Comment by victorsferreira** [comment] 2018-05-01 19:50
@gr2m no unfortunately it's not. I just updated this question with the code I'm using.

**Comment by victorsferreira** [comment] 2018-05-01 19:51
I'm behind a corporate proxy. Does it help?

**Comment by gr2m** [comment] 2018-05-01 19:55
can you record fixtures from the request when you do it with axios (you can do that with https://github.com/node-nock/nock) then edit the recording fixtures to remove everything that might be sensitive and share the recorded fixtures with us?

Maybe someone else has a better idea but that’d be my approach to help you out. It sounds like you have a very unusual setup, maybe your server or the proxy returns a somewhat faulty response that axios handles gracefully but node-fetch does not. 

Another idea would be to try send the request from chrome, I think you can disable the CORS security so it would allow you send cross-origin requests, but I’d have to look it up myself on how to do that

**Comment by victorsferreira** [comment] 2018-05-01 20:12
The problem was caused by the corporate proxy. I could fix it refering to this https://github.com/bitinn/node-fetch/issues/79

Now I pass an `agent` option setting my http proxy.

I believe this should be more accurately documented. 

Stretching my mind I remember we had this problem before a few months ago. Not all endpoints we try to request return this error.

**Comment by bitinn** [comment] 2018-05-30 15:47
I am closing this one, #448 should update readme to give more explicitly directions on working with proxies.

**Closed by bitinn** 2018-05-30 15:47 UTC

**Comment by Jiia** [comment] 2019-03-13 09:53
For the record, I had this same issue and it was caused by creating too many simultaneous fetch requests in a loop, 4200 of them. I ended up queuing the requests. The error ENOTFOUND was really misleading in my case.

**Comment by stanley19** [comment] 2020-10-12 19:46
> For the record, I had this same issue and it was caused by creating too many simultaneous fetch requests in a loop, 4200 of them. I ended up queueing the requests. The error ENOTFOUND was really misleading in my case.

Yes, i got the same error due to too many simultaneous fetch requests too. i had to await fetch function and it solved it.

**Comment by winston0410** [comment] 2020-12-13 15:34
Same here. Tried to send requests in an async pool and it failed.
