### ISSUE TITLE
Please export Blob class and BUFFER symbol

### ISSUE THREAD

**Issue by Gozala** [bitinn/node-fetch#600] opened 2019-04-05 21:07 UTC
Hi,

I'm using node-fetch with https://github.com/RangerMauve/webrun/ and running into problem because `Blob` class can't be referenced nor there is a way to extract bytes from it. Please consider exposing so it could be used.

**Comment by jimmywarting** [comment] 2019-04-05 23:39
Closing as duplicate of #392

**Closed by jimmywarting** 2019-04-05 23:39 UTC
