### ISSUE TITLE
FTP support

### ISSUE THREAD

**Issue by mayank13** [bitinn/node-fetch#636] opened 2019-05-13 12:15 UTC
FTP is not supported by the node-fetch module. Curl supports FTP with and without proxy. For example: curl -x $http_proxy ftp://ftp.gnu.org/README works fine. SImilar support should be added for the node-fetch module.

**Comment by bitinn** [comment] 2019-05-13 12:19
I am going to close this as a duplicate of #75

**Closed by bitinn** 2019-05-13 12:19 UTC
