### ISSUE TITLE
Setting Host headers causes: TypeError: hostHeader.startsWith is not a function

### ISSUE THREAD

**Issue by woky** [bitinn/node-fetch#425] opened 2018-03-13 19:14 UTC
Since version 2.1.0, setting `Host` header causes `fetch` call to fail. This is a minimal example

    const fetch = require('node-fetch');
    (async () => {
        const resp = await fetch('https://google.com', { headers: { 'Host': 'example.com' } });
        console.log(resp);
    })();

that throws following exception:

    (node:5895) UnhandledPromiseRejectionWarning: TypeError: hostHeader.startsWith is not a function
        at calculateServerName (_http_agent.js:240:20)
        at Agent.addRequest (_http_agent.js:155:26)
        at new ClientRequest (_http_client.js:257:16)
        at request (https.js:245:10)
        at /home/user/tmp/node-fetch-host-header/node_modules/node-fetch/lib/index.js:1355:15
        at new Promise (<anonymous>)
        at fetch (/home/user/tmp/node-fetch-host-header/node_modules/node-fetch/lib/index.js:1342:9)
        at /home/user/tmp/node-fetch-host-header/index.js:4:24
        at Object.<anonymous> (/home/user/tmp/node-fetch-host-header/index.js:6:3)
        at Module._compile (module.js:660:30)
    (node:5895) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
    (node:5895) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

In my production code I've also encountered `TypeError: hostHeader.replace is not a function` in almost identical code to the example above.

**Comment by gr2m** [comment] 2018-03-13 19:31
Here is a test case that reproduces the problem: https://runkit.com/gr2m/5aa826566fefc70013b04566

**Comment by bitinn** [comment] 2018-03-14 05:36
Weird, I thought this test should cover it?

https://github.com/bitinn/node-fetch/blob/master/test/test.js#L197-L209

**Comment by woky** [comment] 2018-03-15 20:58
@bitinn Lowercase header key, i.e. `host`, works. I don't know what the `fetch` spec[1] constraints the header keys, but it just felt natural to use what's on the wire in the end.

[1] https://fetch.spec.whatwg.org/

**Comment by bitinn** [comment] 2018-03-16 04:35
We needed a special handling on host header because nodejs http doesn’t allow it in headers (it’s set separately which we handled automatically)

I think we might have missed the capitalize version of Host. Should be easy to normalize.

But it’s always better to use the lowercase header name as nodejs http enforce lowercase header names anyway (not a fetch spec limit).


(From my phone)

**Comment by TimothyGu** [comment] 2018-03-23 00:04
Seems like a duplicate of #416. Let's close this one.

**Closed by TimothyGu** 2018-03-23 00:04 UTC
Labels: bug
