### ISSUE TITLE
Android: Fetch dont't work with "deflate" encoded responses.json() 

### ISSUE THREAD

**Issue by DeFenceD** [bitinn/node-fetch#335] opened 2017-08-30 00:59 UTC
I don't know this wrong trigger either one of the two 'node-fetch' or 'react-native'.

### Is this a bug report?
Android use fetch dont't work with "deflate" encoded responses.json().
I copy the same fetch in browser try to it will response the right encoded json.

### Environment

1. `react-native -v`: 0.47.2
2. `node -v`: 0.8.0
3. `npm -v`: 5.3.0
4. `node-fetch`: 1.7.2

Then, specify:

- Target Platform: Android

- Development Operating System: Windows

- Build tools: Android SDK

### Steps to Reproduce
```
fetch(url, {
              method: 'POST',
              headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json;charset=UTF-8',
              },
              body: JSON.stringify(options),
              compress: true,
            })
              .then((response) => {
                console.log(response);
                return response.json();
              })
              .then((result) => {
                  // result is messy code
              });
```

### Expected Behavior

right to encoded.

### Actual Behavior

return messy code

### Reproducible Demo
```
Unhandled Promise Rejection (id: 0):
SyntaxError: Unexpected token { in JSON at position 0
at parse (<anonymous>)
    at tryCallOne (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13773:12)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13859:15
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5290:19
    at _callTimer (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5204:7)
    at Object.callImmediatesPass (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5432:9)
    at Object.callImmediates (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:5443:21)
    at MessageQueue.__callImmediates (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:4803:16)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:4689:16
    at MessageQueue.__guard (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:4789:9)
```

**Comment by bitinn** [comment] 2017-08-30 04:46
A few things:

- I hope the v0.8.0 node version is a typo, otherwise your Node is way too old. The oldest version we support for node-fetch v1.x is v0.10.0+, and it was already old 2 years ago.

- As for deflate, I think we have taken necessary steps to support not only a valid response but also some slightly invalid ones. If you still have trouble with it, I would say you need to reproduce it in Node.js for us to consider a resolution (sorry about that).

- The call stack isn't useful to us because it's not giving us the right information to troubleshoot.

- It's also possible your JSON is ill formatted. But of course I haven't seen the response JSON to say for sure.

Ref:

- https://github.com/bitinn/node-fetch/blob/1.x/test/test.js#L503-L523
- https://github.com/bitinn/node-fetch/blob/1.x/test/server.js#L79-L95

**Comment by DeFenceD** [comment] 2017-09-04 07:15
1.Sorry, it is real my worry. My Node.js version is 8.0.0, it is my input mistake.
2.I had try the same interface, in browser console tab, in Node.js, it response is OK. But when I use fetch in React Native it will trigger error(State code is 200, is OK, but when I call .json() is broken.)
3.I don't know what should I offer. I think React Native had done secondary encapsulation.
4.I had consider this status, but in  browser console tab, or Node.js, it response is OK. Probably isn't the status.

**Comment by bitinn** [comment] 2017-09-06 04:41
>  I think React Native had done secondary encapsulation.

I think this is the key to our problem. We can only verify this works in Node.js; on Node.js this is just  JSON.parse, it really shouldn't return "messy code".

https://github.com/bitinn/node-fetch/blob/1.x/lib/body.js#L44-L50

I am going to close this, let us know if there is any substantial information for us to troubleshoot.

**Closed by bitinn** 2017-09-06 04:41 UTC
