### ISSUE TITLE
Drop support for Node.js 4.x 

### ISSUE THREAD

**Issue by JustinBeckwith** [bitinn/node-fetch#624] opened 2019-04-28 16:22 UTC
In `engines`, it states that this module supports Node.js 4.x.  I wonder out loud if it's worth ripping off that band aid :) I think this is a great read on the topic:
https://medium.com/@mikeal/stop-supporting-old-releases-70cfa0e04b0c

For many of our modules, we're dropping support for 6 as soon as possible, as may of our own dependencies are starting to drop support.  I'm a little surprised this hasn't gotten y'all in trouble yet with the upgrade of devDependencies :)

**Comment by bitinn** [comment] 2019-04-29 03:29
This is a duplicate of #489, but yes we will drop 4.x and upgrade our devDependencies.

**Comment by Richienb** [comment] 2019-09-08 01:28
Support was dropped in 3.x

**Closed by Richienb** 2019-09-08 01:28 UTC
