### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by geritol** [bitinn/node-fetch#420] opened 2018-03-09 10:18 UTC
Hi I think the package leaks memory.
I have experienced it when doing multiple concurrent requests.
Here is a minimal repro: https://github.com/geritol/node-fetch-leak-repro
I was checking its memory usage with pm2 and have seen pretty aggressive growth in memory utilization. 
- reaches 100m around 70 seconds after start, does not stop.
edit: removed the gif, as the end was cut down, added some numbers.

**Comment by bitinn** [comment] 2018-03-09 10:58
See #83, this is kinda by design, you will need to drain the body if you are not using them. `node-fetch` just doesn't know when you will use the body.

**Comment by jimmywarting** [comment] 2018-03-09 12:23
Aborting should also be a option?

**Comment by geritol** [comment] 2018-03-09 14:09
@bitinn if there are no references to the fetched result it would mean that you do not need it anymore and can be garbage collected or am I wrong here?

**Comment by bitinn** [comment] 2018-03-09 15:38
@geritol https://stackoverflow.com/questions/31957979/node-js-twitter-streaming-memory-leak

**Comment by bitinn** [comment] 2018-03-12 04:07
Closing as memory leak is really not a node-fetch problem.

**Closed by bitinn** 2018-03-12 04:07 UTC

**Comment by geritol** [comment] 2018-03-12 06:19
I do not think this is a pm2 related stuff, garbage collection did happen, but memory is leaked:
I have extended the repro repository with `memwatch-next`. 
If you run the code simply with `node index.js` after a minute or so you will get something like this logged out:
```
Memory leak detected:
 { growth: 1897792,
  reason: 'heap growth over 5 consecutive GCs (29s) - 224.67 mb/hr' }
```
- Based on what I have seen until now for me it is clear that the package leaks memory if the body of the fetched result is not used.
- I think this should not happen as if the fetched result is not referenced anymore, data that belongs to it should be garbage collected. It really seams from the data that it is not.

If this is something "kinda by design" I think it is worth mentioning it on the README. 
But I would still disagree with the fact that this behavior is normal.

**Comment by bitinn** [comment] 2018-03-12 08:19
I don't want to sound harsh, so don't take the following personally:

- If you want to reproduce a memory leak, avoid using `setInterval`, as it's so easy to get yourself trap in another leak (second type of problem): https://auth0.com/blog/four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them/

- If you have to use use `setInterval`, at least use `clearInterval` and force gc at the end, to see if garbage collector is working at expected.

- I am quite certain we don't have an obvious leak (`node-fetch` won't hold instance of responses), but it's up to V8 to decide how to gc it.

- Of course we could have overlooked something. It's up to you to present your case as strongly and convincingly as possible. No one here is payed to do that. The internet is full of people with gc related *memory leak*, you would be better served with a good case!

If you do take time and reproduce this issue, open a new ticket, we will look into it!

**Comment by geritol** [comment] 2018-03-12 09:38
I do not think the use of set interval counts anything here.
But, I have refactored the code to use setTimeout to do these requests for a minute 1 second each.
the result is the same: after 5 gcs memory is leaked.
Please take a look, if you accept this, I will open a new one.
https://github.com/geritol/node-fetch-leak-repro/tree/no-interval

**Comment by bitinn** [comment] 2018-03-12 10:30
I have tested it and the *leak* is coming from you opening too many new connections. `node-fetch` by default doesn't use connection pooling, so by running these many requests you are using more memory (nodejs can't gc that).

I have compare this scripts with and without `agent` passed to `node-fetch`, and it makes an obvious difference (I couldn't trigger the leak event with your repo so I opted to force gc, but looking at `min` and `max` for each case you will see keep-alive keeps the memory stable.)

```
const fetch = require('node-fetch');
const memwatch = require('memwatch-next');
const http = require('http');
const agent = new http.Agent({ 
	keepAlive: true 
})

async function checkEndpoint(endpointURL) {
	let fetchResult;
	try {
		fetchResult = await fetch(endpointURL, { agent: agent });
		memwatch.gc();
	} catch (err) {
		// Err
	}
	return fetchResult;
}

function checkEndpoints(){
	const endpoints = [
		'http://example.com',
	];
	endpoints.forEach( endpoint => checkEndpoint(endpoint));
}

for (let i = 0; i <= 60000; i += 1000) {
	setTimeout(checkEndpoints, i);
}

memwatch.on('stats', (stats) => {
  console.log(stats);
});

memwatch.on('leak', (info) => {
  console.error('Memory leak detected:\n', info);
});
```
