### ISSUE TITLE
default.Headers differs in es6 and cjs output

### ISSUE THREAD

**Issue by jlami** [bitinn/node-fetch#569] opened 2019-01-21 20:08 UTC
Due to the extra rewrite you have in https://github.com/bitinn/node-fetch/blob/e996bdab73baf996cf2dbf25643c8fe2698c3249/build/rollup-plugin.js#L11 there is a difference between the usage of lib/index.js and lib/index.es.js

The cjs format has `default.Headers`, where the es6 version only has Headers as a named export. It is not set on the default export.

This has led to other packages using default.Headers, but when I try to rollup that you get the wrong results. For instance: https://github.com/pouchdb/pouchdb/blob/1da0eb6fbe33ea1aeb55e2b16f479a992ebcb5be/packages/node_modules/pouchdb-fetch/src/fetch.js#L14

You could say that pouchdb uses your library incorrectly. But unless you change the way you export, you are enabling this sort of mistake.

How to reproduce:
test.js:
```
import fetch from 'node-fetch';

console.log(fetch.Headers);
```

rollup.config.js:
```
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  input: './test.js',
  plugins: [nodeResolve()],
  output: {
    file: 'build.js',
    format: 'cjs',
  },
  external: [
    //'node-fetch',//different result when node-fetch is external or not
  ],
};
```

Install npm packages `rollup`, `rollup-plugin-node-resolve` and `node-fetch`
Then rollup without external and the resulting build.js will use the es6 version and not find the Headers.
When setting it as external the resulting cjs will use node-fetch cjs style and will find the Headers.

**Comment by Richienb** [comment] 2019-10-11 22:05
The recent commits show that the issue is now fixed.

**Closed by Richienb** 2019-10-11 22:05 UTC
