### ISSUE TITLE
name: 'FetchError' reason: Parse Error

### ISSUE THREAD

**Issue by Q-Angelo** [bitinn/node-fetch#381] opened 2017-12-09 07:01 UTC
在node-fetch中get方式请求一个地址的时候 如果含有中文字符就提示 reason: Parse Error 同样的地址粘贴在postman里面是没有问题的 想知道这是怎么回事 ？

**Comment by bitinn** [comment] 2017-12-11 08:44
I need more information, or some way to reproduce this.

But first of all check your encoding. Fetch is UTF-8 only.

**Comment by bitinn** [comment] 2017-12-11 09:24
Also this your url contains non-ASCII character, you want to look at this issue: #245

**Comment by TimothyGu** [comment] 2018-02-03 20:23
No movement. Closing.

**Comment by jbraithwaite** [comment] 2018-08-22 23:46
Here is a stack trace for when I ran into this issue:

```
FetchError: request to https://cdn.shopify.com/s/files/1/0224/5643/products/CHEL-FL.PY_FRONT_resize.jpg?v=1532128240 failed, reason: Parse Error
at ClientRequest.<anonymous> (/srv/node_modules/node-fetch/lib/index.js:1345)
at emitOne (events.js:116)
at ClientRequest.emit (events.js:211)
at TLSSocket.socketOnData (_http_client.js:445)
at emitOne (events.js:116)
at TLSSocket.emit (events.js:211)
at addChunk (_stream_readable.js:263)
at readableAddChunk (_stream_readable.js:250)
at TLSSocket.Readable.push (_stream_readable.js:208)
at TLSWrap.onread (net.js:607)
```

**Comment by bitinn** [comment] 2018-11-05 09:17
I tried following on runkit and cannot reproduce it:

```
const fetch = require("node-fetch")
await fetch("https://cdn.shopify.com/s/files/1/0224/5643/products/CHEL-FL.PY_FRONT_resize.jpg?v=1532128240").then(r => r.ok);
```

<img width="719" alt="screen shot 2018-11-05 at 17 16 37" src="https://user-images.githubusercontent.com/1484279/47988974-9b906480-e11e-11e8-9adc-ec52a844ae1b.png">

**Closed by bitinn** 2018-11-05 09:17 UTC
Labels: question
