### ISSUE TITLE
Aborting a fetch

### ISSUE THREAD

**Issue by jimmywarting** [bitinn/node-fetch#95] opened 2016-04-01 07:18 UTC
Implement `AbortController` so we can abort a request

**Comment by bitinn** [comment] 2016-04-01 07:20
Not at the moment, you could set a shorter timeout and handle the error, but no abort.

**Comment by jimmywarting** [comment] 2016-04-01 07:47
:disappointed: Don't want that. I'm doing a long poll request since they don't support sockets...
Would rather have a non standard method until it gets shipped into the spec and deprecate it later

The way AngularJS solved it was with a controller. The timeout could either be a number or a promise
(docs)[https://docs.angularjs.org/api/ng/service/$http#usage]

**Comment by bitinn** [comment] 2016-04-01 08:00
@jimmywarting I don't think `node-fetch` will suit your use case.

Try https://github.com/sindresorhus/got to a similar API, they should allow you to abort.

**Comment by jimmywarting** [comment] 2016-10-15 14:54
maybe `res.body.cancel()` cancels the request?

**Comment by jimmywarting** [comment] 2016-11-13 22:09
Any news about this? I'm pretty certain `res.body.cancel` aborts the download stream doz canceling the response. 

With that you won't be able to abort the hole request/response since you need to fetch the headers first, but i'm fine with that since i only wan't to check against cache headers eg like `if-modified-since`.

I don't know where they stands on cancelable promises but i saw a interesting talk about async/await + cancelable promises (don't remember where - think it was a video of es7 in "weekly javascript")

**Comment by TimothyGu** [comment] 2016-11-13 22:31
Cancelable Promises Proposal is still at Stage 1, and since we don't use Web Streams there are nothing node-fetch can do to support termination except to point users to Node.js's documentation.

For your specific use case, is there a reason why you are not using `HEAD` requests?

**Comment by jimmywarting** [comment] 2016-11-13 23:11
You would avoid making 2 request...

Maybe i can tackle this in an other way... is there something equivalent to web streams cancel method that node's stream has? can i maybe do `res.body.end()`?

**Comment by TimothyGu** [comment] 2016-11-14 05:25
Hmm good point. You _could_ get by with `res.body._dump()`, but ideally we should provide the Node.js `ClientRequest` object as well in `Response` class for its [`abort`](https://nodejs.org/api/http.html#http_request_abort) method.

**Comment by TimothyGu** [comment] 2017-01-12 06:13
The cancelable promises proposal was recently withdrawn (see tc39/proposal-cancelable-promises#70 and whatwg/fetch#27). 

New tracking issue: whatwg/fetch#447.

**Comment by jimmywarting** [comment] 2017-06-02 08:38
Looks like we are getting an [AbortController](https://s3.amazonaws.com/pr-preview/jakearchibald/dom/abort-controller.html#aborting-ongoing-activities)

**Comment by SimenB** [comment] 2017-07-19 08:04
The spec is (semi-)ready.

https://developer.mozilla.org/en-US/docs/Web/API/FetchController

**Comment by TimothyGu** [comment] 2017-07-19 12:33
Everyone, `AbortController` and `AbortSignal` interfaces are now in the [DOM Standard](https://dom.spec.whatwg.org/#aborting-ongoing-activities). Once the corresponding change has been passed in Fetch Standard we will be able to implement it in node-fetch :confetti_ball:

**Comment by bitinn** [comment] 2017-07-20 09:28
@TimothyGu Thx for the heads-up, I feel sorry for not being able to help much as I am fighting on multiple fronts. Time to see if there are any takers on this issue (aka #252).

**Comment by SimenB** [comment] 2017-08-23 09:47
Here are the tests for fetch ran in browser (if you want to check on browser implementation progress) http://wpt.fyi/fetch/api/abort

**Comment by TimothyGu** [comment] 2017-08-23 11:14
The Web Platform Tests were added in https://github.com/w3c/web-platform-tests/pull/6484. An overview of WHATWG's design of aborting fetch is available at https://github.com/w3c/web-platform-tests/pull/6484#issuecomment-315775251. If it's not too hard we should look at integrating WPT into this module.

IMO we should try to implement (or endorse) a version of `AbortController` that can be used independent of node-fetch, like https://www.npmjs.com/package/abortcontroller-polyfill (/cc @jimmywarting).

**Comment by jimmywarting** [comment] 2017-08-23 11:54
That polyfill is depending on browser due to extending DOM's event emiter.
One thing i don't like about that polyfill is that it tries to monkey patch fetch - i think it would be useful to have a independent module that other libs also can use.

I could release a independent module that mostly look like this:

```js
const EventEmitter = require('events')

class AbortSignal extends EventEmitter {
  constructor() {
    super()
    this.aborted = false
  }
}

class AbortController {
  constructor() {
    this.signal = new AbortSignal()
  }
  abort() {
    this.signal.aborted = true
    this.signal.emit(new Event('abort'))
  }
}
```

It would feel a bit more nicer to have a node emitter also

**Comment by TimothyGu** [comment] 2017-08-23 11:57
@jimmywarting Yeah it would feel more natural given node-fetch's server-side context. I've already filed https://github.com/mo/abortcontroller-polyfill/issues/2. Regarding monkey patching `fetch`, that could be lifted into a separate file to be `require`d.

**Comment by jimmywarting** [comment] 2017-08-23 11:59
I will make a such package now and probably call it `abortcontroller`

**Comment by jimmywarting** [comment] 2017-08-23 12:01
the abortcontroller package don't have to do anything with regards to fetch, it's just node-fetch that has to use it correctly

**Comment by bradisbell** [comment] 2017-12-28 08:25
For what it's worth, one way to cancel a Fetch in-browser is to consume the body as a stream and then close the stream.  Calling `.terminate()` on the `response.body` stream from this Fetch module doesn't have the same effect.

**Comment by jimmywarting** [comment] 2017-12-28 17:10
Good to know, although you would only be able to abort the download, not the upload

**Comment by joaovieira** [comment] 2018-02-04 19:23
While working on the browser `fetch` polyfill (https://github.com/github/fetch/pull/592) I made [abortcontroller-polyfill](https://github.com/mo/abortcontroller-polyfill) universal, so it can also work within web workers and on Node.js:

https://github.com/mo/abortcontroller-polyfill/pull/12
https://github.com/mo/abortcontroller-polyfill/pull/13
https://github.com/mo/abortcontroller-polyfill/pull/14

While you could have nicer implementations for browser (using `document`) and node (using `EventEmitter`) separately, it would still not work for web workers. Having a universal shared module seems 👍 

I'm also of the opinion this should only polyfill `AbortController` and not patch `fetch` - the latter being done by both fetch polyfills (browser and Node).

**Comment by TimothyGu** [comment] 2018-03-27 20:43
A WIP is now available in https://github.com/bitinn/node-fetch/pull/437.

**Comment by mika-fischer** [comment] 2018-03-29 08:28
I can confirm that #437 fixes my issue in #438. However, a few questions:
1) AFAICT, I always have to pass a signal and keep the controller, there's no way to use the one that's in the Request object by default to abort the request or response. This might be by design and is fine, just making sure I'm not missing anything.
2) If I use a global AbortController for all requests, it seems that every fetch adds a listener to that controller, which is never removed. This will create problems in the long run, no? See my comment in the PR.

**Comment by heri16** [comment] 2018-06-14 11:40
Does anyone have sample code for the WIP? Is this the API?

```JavaScript
const controller = new AbortController();
const signal = controller.signal;
controller.abort();
fetch(Request("http://api.github.com", {signal}))
  .then(r => r.json())
  .then(j => console.log(j))
  .catch(err => {
      if (err.name === 'AbortError') {
          console.log('aborted');
      }
  })
```

**Comment by heri16** [comment] 2018-06-14 12:45
> As far as HTTP is concerned, "cancelling the response" means the same thing as discarding the rest of the response and closing the socket. Both of these things are accomplished in Node.js with req.abort() -- aborting the request itself.

#437 seem to only abort the request, but not be able to abort the response stream?

**Comment by heri16** [comment] 2018-06-14 12:50
Alright, found the http.request.abort() line. https://github.com/bitinn/node-fetch/blob/a823a1ef74a34b9b6b25ed6cb790de8c40e4ef38/src/index.js#L68

**Comment by heri16** [comment] 2018-06-22 04:33
I am trying to abort slow `res.json()`.
These lines do not work for me.
 
```javascript
const controller = new AbortController()
const res = await fetch(url, {
    ...options,
    signal: controller.signal,
}).then((res) => {
    res.abortController = controller
    return res
})
setImmediate(() => res.abortController.abort())
res.body.on('error') # nothing is caught
res.body.on('abort') # nothing is caught
await res.json()
```

**Comment by bitinn** [comment] 2018-11-13 06:42
`AbortSignal` support is now merged and released as `v2.3.0`. You can use any valid implementation of `AbortController` to create the signal.

See README for details and examples.

**Closed by bitinn** 2018-11-13 06:42 UTC
Labels: standard landed

**Comment by muscaiu** [comment] 2020-06-23 10:25
What about Pausing/Resuimg a download?

**Comment by ml054** [comment] 2020-06-23 10:28
maybe through2 might be helpful for doing that?

**Comment by muscaiu** [comment] 2020-06-23 10:40
Just looked at though2 and can't think how i could use it.

I have a question [here](https://github.com/node-fetch/node-fetch/issues/752) about it pausing/resuming a download.
If you have any example, i would really apreciate it, thanks!
