### ISSUE TITLE
Access Request Headers

### ISSUE THREAD

**Issue by shivanan** [bitinn/node-fetch#393] opened 2018-02-02 10:47 UTC
For debugging purposes, I would like to access the final set of headers that are sent with a request (we can already access response headers, of course).

I feel like this could be done by taking the `options` object being passed to `send()` and send it back to the caller (maybe via a callback or some other means).

Is this a useful feature to have? Can I submit a pull request for this?

**Comment by jimmywarting** [comment] 2018-02-02 11:06
closing as duplicate of https://github.com/bitinn/node-fetch/issues/284

**Closed by jimmywarting** 2018-02-02 11:06 UTC

**Comment by ehmicky** [comment] 2018-08-24 08:29
I would like to reopen this as I believe #284, while similar, is slightly different.

This PR does not ask for exposing the underlying Node.js request, but instead to be able to know which extra set of headers where added by `node-fetch`. 

The reason I would use it is because my code is logging every HTTP request. I want to log the exact HTTP request, i.e. including any extra headers by libraries I might be using. At the moment this is not possible with `node-fetch`.
